# suppress inspection "UnusedProperty" for whole file
# suppress inspection "WrongPropertyKeyValueDelimiter" for whole file

[versions]
java                          = "17"
kotlin                        = "1.9.20"

compileSdk                    = "34"
minSdk                        = "26"
targetSdk                     = "34"

coreKtx                       = "1.12.0"
activityCompose               = "1.8.1"
navigationCompose             = "2.7.5"

[plugins]
#kotlinPlugin                  = "org.jetbrains.kotlin.android:1.8.10"
#androidApp                    = "com.android.application:8.1.4"
#crashlytics                   = "com.google.firebase.crashlytics:2.8.1"
#googleServices                = "com.google.gms.google-services:4.3.15"
#performance                   = "com.google.firebase.firebase-perf:1.4.1"
#apollo                        = "com.apollographql.apollo:2.5.14"
#navigationSafeArgs            = "androidx.navigation.safeargs.kotlin:2.5.0"


[libraries]
androidx-activity-compose     = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx             = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-navigation-compose   = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
kotlin-stdLib                 = { module ="org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-lifecycleRuntime       = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2"
kotlin-coroutinesCore         = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
kotlin-coroutinesTest         = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.3"
kotlin-coroutinesRxAdapter    = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3:1.7.1"

koin-android                  = "io.insert-koin:koin-android:3.4.3"

okhttp                        = "com.squareup.okhttp3:okhttp:4.11.0"
okhttp-logging                = "com.squareup.okhttp3:logging-interceptor:4.11.0"

gson                          = "com.google.code.gson:gson:2.10.1"

retrofit-core                 = "com.squareup.retrofit2:retrofit:2.9.0"
retrofit-scalars              = "com.squareup.retrofit2:converter-scalars:2.9.0"
retrofit-rxJavaAdapter        = "com.squareup.retrofit2:adapter-rxjava3:2.9.0"
retrofit-gsonConverter        = "com.squareup.retrofit2:converter-gson:2.9.0"

glide-core                    = "com.github.bumptech.glide:glide:4.15.1"

timber                        = "com.jakewharton.timber:timber:4.7.1"

firebase-analytics            = "com.google.firebase:firebase-analytics-ktx:21.5.0"
firebase-crashlytics          = "com.google.firebase:firebase-crashlytics-ktx:18.6.0"
firebase-messaging            = "com.google.firebase:firebase-messaging-ktx:23.3.1"
firebase-perf                 = "com.google.firebase:firebase-perf-ktx:20.5.1"

shimmer                       = "com.facebook.shimmer:shimmer:0.5.0"

mockk                         = "io.mockk:mockk:1.13.5"
junit                         = "junit:junit:4.13.2"
androidx-junit                = "androidx.test.ext:junit:1.1.5"
androidx-junit-ktx            = "androidx.test.ext:junit-ktx:1.1.5"
androidx-espresso-core        = "androidx.test.espresso:espresso-core:3.5.1"
robolectric                   = "org.robolectric:robolectric:4.11.1"